spring:
   application:
      name: department-service
   config:
      import: "optional:configserver:http://localhost:8088"
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/department-service?createDatabaseIfNotExist=true
   jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQLDialect