#DB connections
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ecommerce

server:
  port : 8081

#jwt credentials
jwt.secret.key : #####################
jwt.expiration.in.milliseconds : 172800000

      